version: '3'
services:

  # Django application container
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: hostal.settings
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase  # Nombre de la base de datos
      POSTGRES_USER: myuser    # Nombre de usuario de la base de datos
      POSTGRES_PASSWORD: mypassword  # Contraseña de la base de datos
    ports:
      - "5432:5432"  # Puerto de PostgreSQL
  